name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php-versions:
          - '5.6'
          - '7.2'
          - '7.4'
          - '8.1'
        include:
          - php-version: '8.2'
            experimental: true

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP for Version ${{ matrix.php-versions }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
    
    - name: Check syntax error in sources
      run: find ./ -type f -name '*.php' -print0 | xargs -0 -L 1 -P 4 -- php -l
